xml_mirror: /mirror
mysql: "root:test@tcp(mysql:3306)/cache"
port: ":6666"
redis_address: "pub-redis-19741.eu-central-1-1.1.ec2.redislabs.com:19741"
routine_count: 2
mongo: "mongodb://mongo:27017"
mongo_db: "admin"
mongo_err_collection: "file_process_errors"
service_preffix: "mgo_service_"
service_port: "3131"
loging_url: true

log_hook:
    log_host: production
    log_system: queue_reader
    log_db_host: "mongodb://mongo:27017"
    log_dbname: admin
    log_collection: app_logs

ws_config:
    ws_secret: some-secret-key
    ws_host: centrifugo
    ws_port: "8000"
    ws_channel: "events"